### ISSUE TITLE
submit.py执行报错

### ISSUE THREAD

**Issue by DawnCaiYuan** [Tshzzz/jinnan_yolo_baseline#1]
Traceback (most recent call last):
  File "submit.py", line 50, in <module>
    pred_boxes, pred_conf = model(img)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/jinnan_yolo_baseline/src/yolov2.py", line 45, in forward
    pred = self.decoder((pred_cls, pred_conf, pred_bboxes))
  File "/jinnan_yolo_baseline/src/box_coder.py", line 122, in __call__
    cls_prob = pred_cls[:, cls].float() * pred_conf[:, 0]
IndexError: too many indices for tensor of dimension 1

**Comment by Tshzzz** [comment]
请问你用的pytorch是什么版本？是否修改过代码。这个问题本身应该是，pred_cls或者pred_conf的维度不是2维。

**Comment by DawnCaiYuan** [comment]
用的是pytorch0.4,代码并没有修改

**Comment by zhouzhubin** [comment]
我也是这个问题,我用200的epoch的模型,运行是没有问题的,但是用290的模型,就会出现上面的问题了

**Comment by Tshzzz** [comment]
不好意思，我检查一下。

**Comment by zhouzhubin** [comment]
谢谢了啊,麻烦了

**Comment by Tshzzz** [comment]
> 谢谢了啊,麻烦了

我训练到290个epoch。也没什么问题。你可以把训练的 log发给我一下吗？695809401@qq.com。

**Comment by zhouzhubin** [comment]
我是在vaild.py上用200的epoch,没有问题,290出错.在submit.py上不管200的还是290都是会出现上面的问题.那个log发给你了

**Comment by Tshzzz** [comment]
我使用的是pytorch 1.0.1，程序在我这里没有问题。可能因为你们使用的是pytorch 0.4导致的问题？我修改的代码，尝试去解决这个问题，你们可以去试试。

**Comment by abraham2001** [comment]
我在cls_prob = pred_cls[:, cls].float() * pred_conf[:, 0]这行代码前加了
if pred_cls.shape == torch.Size([0]):
        continue
可以执行

**Comment by Tshzzz** [comment]
> 我在cls_prob = pred_cls[:, cls].float() * pred_conf[:, 0]这行代码前加了
> if pred_cls.shape == torch.Size([0]):
> continue
> 可以执行

嗯嗯！非常感谢
